(()=>{
let video,stream,timer,worker,busy=false,locked=false,closed=true,last="",stable=0,photo="",matches=[],generation=0;
const style=document.createElement("style");style.textContent="#scanLaunch{position:fixed;right:14px;bottom:80px;z-index:200;background:#ffd447;color:#111;padding:14px;border:0;border-radius:30px;font-weight:800}#scanPanel{position:fixed;inset:0;z-index:9999;background:#080a10;color:white;overflow:auto;padding:15px}#scanPanel .scanInner{max-width:550px;margin:auto}#scanPanel .scanFrame{position:relative;background:black;border-radius:14px;overflow:hidden;aspect-ratio:3/4;margin:12px 0}#scanPanel video,#scanPanel .scanStill{width:100%;height:100%;object-fit:contain}#scanPanel .scanResult{position:absolute;bottom:8px;left:8px;right:8px;padding:12px;background:#111b2bf2;border:1px solid #ffd447;border-radius:10px;max-height:85%;overflow:auto}#scanPanel button{padding:10px;margin:4px;border-radius:8px;background:#263248;color:white;border:1px solid #59647a;font-weight:700}#scanPanel .primary{background:#ffd447;color:#111}#scanPanel select,#scanPanel input{padding:10px;background:#263248;color:white;max-width:100%}#scanPanel .scanFound{display:flex;gap:12px;align-items:center}#scanPanel .scanFound img{width:75px}";document.head.append(style);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&#39;"}[c]));
const normal=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase();
const root=()=>document.querySelector("#scanPanel");
const report=s=>{const el=root()?.querySelector("#scanStatus");if(el)el.textContent=s};
function capture(){if(!video||video.readyState<2)return "";const c=document.createElement("canvas");c.width=640;c.height=Math.round(video.videoHeight*640/video.videoWidth);c.getContext("2d").drawImage(video,0,0,c.width,c.height);return c.toDataURL("image/jpeg",.88)}
function resume(){generation++;locked=false;stable=0;last="";root()?.querySelector(".scanStill")?.remove();const e=root()?.querySelector("#scanResult");if(e)e.innerHTML="";if(video)video.style.display="";loop(650)}
function loop(ms=1800){clearTimeout(timer);if(!closed&&!locked)timer=setTimeout(scan,ms)}
async function ocr(){if(worker)return worker;if(!window.Tesseract){await new Promise((ok,fail)=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js";s.onload=ok;s.onerror=()=>fail(Error("No se pudo cargar OCR"));document.head.append(s)})}const created=await Tesseract.createWorker("eng");if(closed){await created.terminate();throw Error("escáner cerrado")}worker=created;return worker}
function rank(txt){const raw=normal(txt),flat=raw.replace(/[^A-Z0-9]/g,""),words=new Set(raw.split(/[^A-Z0-9]+/).filter(Boolean));return state.cards.map(c=>{const id=normal(baseId(c.id)).replace(/[^A-Z0-9]/g,""),n=normal(c.name),ws=n.split(/[^A-Z0-9]+/).filter(x=>x.length>2);let score=(ws.filter(x=>words.has(x)).length/Math.max(1,ws.length))*35;if(id&&new RegExp("(?:^|[^A-Z0-9])"+id+"(?:$|[^A-Z0-9])").test(raw.replace(/[-_ ]+/g,"")))score+=90;else if(id&&flat.includes(id)&&id.length>=7)score+=75;if(raw.includes(n)&&n.length>3)score+=30;return {c,score}}).filter(x=>x.score>12).sort((a,b)=>b.score-a.score).slice(0,18)}
function pixelVector(im){const c=document.createElement("canvas");c.width=16;c.height=24;const g=c.getContext("2d",{willReadFrequently:true});g.drawImage(im,0,0,16,24);let p=g.getImageData(0,0,16,24).data,a=[];for(let i=0;i<p.length;i+=4)a.push((p[i]+p[i+1]+p[i+2])/765);return a}
function loadImage(url){return new Promise((ok,fail)=>{const i=new Image();i.crossOrigin="anonymous";i.onload=()=>ok(i);i.onerror=fail;i.src=url;setTimeout(()=>fail(Error("timeout")),1400)})}
async function rerank(list){if(!list.length)return list;try{const target=pixelVector(await loadImage(photo));const subset=await Promise.all(list.slice(0,8).map(async x=>{try{const sample=pixelVector(await loadImage(imageCdnUrl(x.c)));let d=0;for(let i=0;i<sample.length;i++)d+=Math.abs(sample[i]-target[i]);return {...x,score:x.score+14*(1-d/sample.length)}}catch{return x}}));return subset.sort((a,b)=>b.score-a.score).concat(list.slice(8))}catch{return list}}
async function scan(){if(closed||locked||busy)return;const turn=generation;busy=true;try{const shot=capture();if(!shot){loop(500);return}photo=shot;report("Reconociendo texto e ilustración…");const engine=await ocr();if(closed||locked||turn!==generation)return;const result=await engine.recognize(shot);if(closed||locked||turn!==generation)return;matches=await rerank(rank(result.data.text));if(closed||locked||turn!==generation)return;if(!matches.length||matches[0].score<30){stable=0;report("Buscando… Centra la carta y evita los reflejos.");return}const key=baseId(matches[0].c.id);stable=last===key?stable+1:1;last=key;if(stable>=3){locked=true;show(matches[0].c)}else report("Posible "+matches[0].c.name+"; comprobando…")}catch(e){report("Reconocimiento no disponible: "+e.message+". Usa búsqueda manual.")}finally{busy=false;if(!locked&&!closed)loop()}}
function show(c){
 if(!c)return;locked=true;clearTimeout(timer);
 let shot=root().querySelector(".scanStill");if(!shot){shot=document.createElement("img");shot.className="scanStill";root().querySelector(".scanFrame").prepend(shot)}shot.src=photo;video.style.display="none";
 const versions=state.cards.filter(x=>baseId(x.id)===baseId(c.id)),owned=versions.reduce((n,x)=>n+qty(x.id),0),target=playsetTarget(c);
 const alt=[...new Map(matches.map(x=>[x.c.id,x.c])).values()].filter(x=>baseId(x.id)!==baseId(c.id)).slice(0,4);
 const box=root().querySelector("#scanResult");box.innerHTML='<div class="scanResult"><div class="scanFound"><img src="'+esc(imageCdnUrl(c))+'" alt=""><div><strong>'+esc(c.name)+'</strong><div>'+esc(baseId(c.id))+'</div><div>Esta versión: '+qty(c.id)+' copias</div><div>Total: '+owned+' · '+(owned>=target?'Playset completo':'Faltan '+(target-owned)+' para playset')+'</div></div></div><p>Selecciona la impresión exacta:</p><select id="scanVariant">'+versions.map(x=>'<option value="'+esc(x.id)+'" '+(x.id===c.id?'selected':'')+'>'+esc(x.id)+' · '+esc(variantKindOf(x))+' · '+esc(printSetOf(x))+'</option>').join("")+'</select><div><button class="primary" id="scanAdd">+1 y continuar</button><input type="number" id="scanCount" value="2" min="1" max="99" style="width:62px"><button class="primary" id="scanMultiple">Añadir copias y continuar</button><button id="scanSkip">Cerrar y continuar</button></div>'+(alt.length?'<details><summary>¿No es la carta correcta? Otras coincidencias</summary>'+alt.map(x=>'<button data-other="'+esc(x.id)+'">'+esc(x.name)+' · '+esc(x.id)+'</button>').join("")+'</details>':'')+'<button id="scanManualResult">Buscar manualmente</button></div>';
 box.querySelector("#scanVariant").onchange=e=>show(card(e.target.value));
 const add=n=>{const id=box.querySelector("#scanVariant").value,numeric=Number(n);if(!Number.isInteger(numeric)||numeric<1||numeric>99){report("Introduce entre 1 y 99 copias.");return}setQty(id,Math.min(99,qty(id)+numeric));resume();report("Añadidas "+numeric+" copia(s) de "+id+". Continúa escaneando.")};
 box.querySelector("#scanAdd").onclick=()=>add(1);box.querySelector("#scanMultiple").onclick=()=>add(box.querySelector("#scanCount").value);box.querySelector("#scanSkip").onclick=resume;box.querySelector("#scanManualResult").onclick=manual;
 box.querySelectorAll("[data-other]").forEach(b=>b.onclick=()=>show(card(b.dataset.other)));report("Imagen congelada: confirma la versión antes de añadir.");
}
function manual(){locked=true;clearTimeout(timer);const area=root().querySelector("#scanManualArea");area.innerHTML='<input id="scanSearch" placeholder="Nombre o código"><div id="scanHits"></div>';const inp=area.querySelector("input");inp.oninput=()=>{const q=normal(inp.value),hits=area.querySelector("#scanHits");hits.innerHTML=q.length<2?"":state.cards.filter(c=>normal(c.id+" "+c.name).includes(q)).slice(0,25).map(c=>'<button data-hit="'+esc(c.id)+'">'+esc(c.id)+' '+esc(c.name)+'</button>').join("");hits.querySelectorAll("[data-hit]").forEach(b=>b.onclick=()=>{photo=capture()||photo;show(card(b.dataset.hit));area.innerHTML=""})};inp.focus();report("Busca y elige una carta para añadirla.")}
async function open(){if(root())return;if(!state.cards?.length){alert("El catálogo no ha cargado");return}generation++;closed=false;locked=false;stable=0;const openGeneration=generation;const ui=document.createElement("section");ui.id="scanPanel";ui.innerHTML='<div class="scanInner"><h2>Escáner de cartas <button id="scanClose">✕ Cerrar</button></h2><p id="scanStatus">Abriendo cámara…</p><div class="scanFrame"><video autoplay muted playsinline></video><div id="scanResult"></div></div><button id="scanRetry">Reanudar reconocimiento</button><button id="scanManual">Buscar manualmente</button><div id="scanManualArea"></div><p style="font-size:12px;color:#aab6c8">OCR y comparación visual local. Comprueba la impresión antes de guardar; las versiones parecidas pueden confundirse.</p></div>';document.body.append(ui);video=ui.querySelector("video");ui.querySelector("#scanClose").onclick=close;ui.querySelector("#scanRetry").onclick=resume;ui.querySelector("#scanManual").onclick=manual;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});if(closed||openGeneration!==generation){stream.getTracks().forEach(t=>t.stop());return}video.srcObject=stream;await video.play();if(!closed&&openGeneration===generation)loop(400)}catch(e){report("No se pudo abrir la cámara. Necesitas HTTPS y permisos: "+e.message)}}
function close(){generation++;closed=true;clearTimeout(timer);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;if(worker){worker.terminate();worker=null}root()?.remove();video=null}
function init(){if(document.querySelector("#scanLaunch"))return;const b=document.createElement("button");b.id="scanLaunch";b.textContent="📷 Escanear cartas";b.onclick=open;document.body.append(b)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();